[package]
name = "svd2cpp"
version = "0.1.0"
edition = "2021"

[dependencies]
svd-parser = "0.14.9"
roxmltree = "0.20"
anyhow = "1.0.58"
thiserror = "2.0.12"
serde_json = { version = "1.0", features = ["preserve_order"] }
svd-rs = { version = "0.14.10", features = ["serde"] }