[project]
name = "svd2cpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pytest>=8.3.5",
    "xmltodict>=0.14.2",
]
